version: 'Build #{build} at {branch}'
pull_requests: 
    do_not_increment_build_number: true
configuration: Debug
platform: Any CPU
build:
    verbosity: minimal
clone_folder: C:\
environment:
  PATH: C:\Python27\;C:\Program Files (x86)\Git\bin;C:\Program Files (x86)\Git\cmd
