version: 'Build #{build} at {branch}'
pull_requests: 
    do_not_increment_build_number: true
configuration: Debug
platform: Any CPU
build:
    verbosity: minimal
test_script:
- ps: cd home
clone_folder: C:\
environment:
  PATH: C:\Python27\
